const carData = {
  carBrands: {
    "Abarth": [
      "124 Spider",
      "500",
      "500C",
      "595",
      "595C",
      "595 Competizione",
      "595 Turismo",
      "600e",
      "695",
      "695C",
      "Grande Punto",
      "Punto Evo",
      "Other"
    ],
    "Alfa Romeo": [
      "145",
      "146",
      "147",
      "155",
      "156",
      "159",
      "164",
      "166",
      "33",
      "4C",
      "75",
      "8C",
      "90",
      "Alfasud",
      "Alfetta",
      "Brera",
      "Crosswagon",
      "Giulia",
      "Giulietta",
      "GT",
      "GTV",
      "Junior",
      "MiTo",
      "Spider",
      "Sprint",
      "Stelvio",
      "Tonale",
      "Other"
    ],
    "Alpina": [
      "B10",
      "B12",
      "B3",
      "B4",
      "B5",
      "B6",
      "B7",
      "B8",
      "D10",
      "D3",
      "D3 S",
      "D4",
      "D4 S",
      "D5",
      "Roadster S",
      "XB7",
      "XD3",
      "XD4",
      "Other"
    ],
    "Alpine": [
      "A110",
      "A290",
      "Other"
    ],
    "Aston Martin": [
      "AR1",
      "Cygnet",
      "DB",
      "DB11",
      "DB12",
      "DB7",
      "DB9",
      "DBS",
      "DBX",
      "Lagonda",
      "Rapide",
      "V12 Vantage",
      "V8 Vantage",
      "Vanquish",
      "Virage",
      "Other"
    ],
    "Audi": [
      "100",
      "200",
      "80",
      "90",
      "A1",
      "A2",
      "A3",
      "A4",
      "A4 Allroad",
      "A5",
      "A6",
      "A6 Allroad",
      "A6 e-tron",
      "A7",
      "A8",
      "Cabriolet",
      "Coupé",
      "e-tron",
      "e-tron GT",
      "Q2",
      "Q3",
      "Q4",
      "Q4 e-tron",
      "Q5",
      "Q6 e-tron",
      "Q7",
      "Q8",
      "Q8 e-tron",
      "quattro",
      "R8",
      "RS2",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS e-tron GT",
      "RSQ3",
      "RSQ8",
      "S1",
      "S2",
      "S3",
      "S4",
      "S5",
      "S6",
      "S6 e-tron",
      "S7",
      "S8",
      "SQ2",
      "SQ5",
      "SQ6 e-tron",
      "SQ7",
      "SQ8",
      "SQ8 e-tron",
      "TT (alle)",
      "TT",
      "TT RS",
      "TTS",
      "V8",
      "Other"
    ],
    "Bentley": [
      "Arnage",
      "Azure",
      "Bentayga",
      "Brooklands",
      "Continental",
      "Continental Flying Spur",
      "Continental GT",
      "Continental GTC",
      "Continental Supersports",
      "Eight",
      "Flying Spur",
      "Mulsanne",
      "S2",
      "Turbo R",
      "Turbo RT",
      "Turbo S",
      "Other"
    ],
    "BMW": [
      // 1 Series
      "1 Series (All)",
      "114",
      "116",
      "118",
      "120",
      "123",
      "125",
      "128",
      "130",
      "135",
      "1er M Coupé",
      // standalone
      "2002",
      // 2 Series
      "2 Series (All)",
      "214 Active Tourer",
      "214 Gran Tourer",
      "216",
      "216 Active Tourer",
      "216 Gran Coupé",
      "218",
      "218 Active Tourer",
      "218 Gran Coupé",
      "220",
      "220 Active Tourer",
      "220 Gran Coupé",
      "223 Active Tourer",
      "225",
      "225 Active Tourer",
      "228",
      "230",
      "2er Gran Coupé",
      // 3 Series
      "3 Series (All)",
      "315",
      "316",
      "318",
      "318 Gran Turismo",
      "320",
      "320 Gran Turismo",
      "323",
      "324",
      "325",
      "325 Gran Turismo",
      "328",
      "328 Gran Turismo",
      "330",
      "330 Gran Turismo",
      "335",
      "335 Gran Turismo",
      "340",
      "340 Gran Turismo",
      "ActiveHybrid 3",
      // 4 Series
      "4 Series (All)",
      "418",
      "418 Gran Coupé",
      "420",
      "420 Gran Coupé",
      "425",
      "425 Gran Coupé",
      "428",
      "428 Gran Coupé",
      "430",
      "430 Gran Coupé",
      "435",
      "435 Gran Coupé",
      "440",
      "440 Gran Coupé",
      // 5 Series
      "5 Series (All)",
      "518",
      "520",
      "520 Gran Turismo",
      "523",
      "524",
      "525",
      "528",
      "530",
      "530 Gran Turismo",
      "535",
      "535 Gran Turismo",
      "540",
      "545",
      "550",
      "550 Gran Turismo",
      "ActiveHybrid 5",
      // 6 Series
      "6 Series (All)",
      "620 Gran Turismo",
      "628",
      "630",
      "630 Gran Turismo",
      "633",
      "635",
      "640",
      "640 Gran Coupé",
      "640 Gran Turismo",
      "645",
      "650",
      "650 Gran Coupé",
      // 7 Series
      "7 Series (All)",
      "725",
      "728",
      "730",
      "732",
      "735",
      "740",
      "745",
      "750",
      "760",
      "ActiveHybrid 7",
      // others
      "840",
      "850",
      "i3",
      "i4",
      "i5",
      "i7",
      "i8",
      "iX",
      "iX1",
      "iX2",
      "iX3",
      // M Models
      "M Models (All)",
      "M135",
      "M140i",
      "M2",
      "M235",
      "M240i",
      "M3",
      "M340d",
      "M340i",
      "M4",
      "M440",
      "M5",
      "M550",
      "M6",
      "M760",
      "M8",
      "M850",
      // X Series
      "X Series (All)",
      "ActiveHybrid X6",
      "X1",
      "X2",
      "X3",
      "X3 M",
      "X3 M40",
      "X3 M50",
      "X4",
      "X4 M",
      "X4 M40",
      "X5",
      "X5 M",
      "X5 M50",
      "X5 M60",
      "X6",
      "X6 M",
      "X6 M50",
      "X6 M60",
      "X7",
      "X7 M50",
      "X7 M60",
      "XM",
      // Z Series
      "Z Series (All)",
      "Z1",
      "Z3",
      "Z3 M",
      "Z4",
      "Z4 M",
      "Z4 M40i",
      "Z8",
      // fallback
      "Other"
    ],
    "Bugatti": [
      "Chiron",
      "EB 110",
      "Veyron",
      "Other"
    ],
    "Buick": [
      "Century",
      "Electra",
      "Enclave",
      "La Crosse",
      "Le Sabre",
      "Park Avenue",
      "Regal",
      "Riviera",
      "Roadmaster",
      "Skylark",
      "Other"
    ],
    "BYD": [
      "ATTO 2",
      "ATTO 3",
      "DOLPHIN",
      "ETP 3",
      "HAN",
      "SEAL",
      "SEALION 7",
      "SEAL U",
      "TANG",
      "Other"
    ],
    "Cadillac": [
      "Allante",
      "ATS",
      "BLS",
      "CT5",
      "CT6",
      "CTS",
      "Deville",
      "Eldorado",
      "Escalade",
      "Fleetwood",
      "Seville",
      "SRX",
      "STS",
      "XLR",
      "XT4",
      "XT5",
      "XT6",
      "Other"
    ],
    "Chevrolet": [
      "2500",
      "Alero",
      "Astro",
      "Avalanche",
      "Aveo",
      "Beretta",
      "Blazer",
      "C1500",
      "Camaro",
      "Caprice",
      "Captiva",
      "Cavalier",
      "Chevelle",
      "Chevy Van",
      "Citation",
      "Colorado",
      "Corsica",
      "Cruze",
      "El Camino",
      "Epica",
      "Evanda",
      "Express",
      "G",
      "HHR",
      "Impala",
      "K1500",
      "K30",
      "Kalos",
      "Lacetti",
      "Lumina",
      "Malibu",
      "Matiz",
      "Niva",
      "Nubira",
      "Orlando",
      "Rezzo",
      "S-10",
      "Silverado",
      "Spark",
      "SSR",
      "Suburban",
      "Tahoe",
      "Trailblazer",
      "Trans Sport",
      "Traverse",
      "Trax",
      "Venture",
      "Volt",
      "Other"
    ],
    "Chrysler": [
      "200",
      "300C",
      "300 M",
      "Aspen",
      "Crossfire",
      "Daytona",
      "ES",
      "Grand Voyager",
      "GS",
      "GTS",
      "Imperial",
      "Le Baron",
      "Neon",
      "New Yorker",
      "Pacifica",
      "PT Cruiser",
      "Saratoga",
      "Sebring",
      "Stratus",
      "Valiant",
      "Viper",
      "Vision",
      "Voyager",
      "Other"
    ],
    "Citroen": [
      "2 CV",
      "AMI",
      "AX",
      "Berlingo",
      "BX",
      "C1",
      "C2",
      "C3",
      "C3 Aircross",
      "C3 Picasso",
      "C4",
      "C4 Aircross",
      "C4 Cactus",
      "C4 Picasso",
      "C4 SpaceTourer",
      "C4 X",
      "C5",
      "C5 Aircross",
      "C5 X",
      "C6",
      "C8",
      "C-Crosser",
      "C-Elysée",
      "CX",
      "C-Zero",
      "DS",
      "DS3",
      "DS4",
      "DS4 Crossback",
      "DS5",
      "ë-Berlingo",
      "ë-C3",
      "ë-C3 Aircross",
      "ë-C4",
      "ë-C4 X",
      "E-MEHARI",
      "ë-Spacetourer",
      "Evasion",
      "Grand C4 Picasso / SpaceTourer",
      "GSA",
      "Jumper",
      "Jumpy",
      "Nemo",
      "SAXO",
      "SM",
      "SpaceTourer",
      "Visa",
      "Xantia",
      "XM",
      "Xsara",
      "Xsara Picasso",
      "ZX",
      "Other"
    ],
    "Corvette": [
      "C1",
      "C2",
      "C3",
      "C4",
      "C5",
      "C6",
      "C7",
      "C8",
      "Z06",
      "ZR 1",
      "Other"
    ],
    "Cupra": [
      "Arona",
      "Ateca",
      "Born",
      "Formentor",
      "Ibiza",
      "Leon",
      "Tavascan",
      "Terramar",
      "Other"
    ],
    "Dacia": [
      "Bigster",
      "Dokker",
      "Duster",
      "Jogger",
      "Lodgy",
      "Logan",
      "Logan Pick-Up",
      "Pick Up",
      "Sandero",
      "Spring",
      "Other"
    ],
    "Daewoo": [
      "Espero",
      "Evanda",
      "Kalos",
      "Korando",
      "Lacetti",
      "Lanos",
      "Leganza",
      "Matiz",
      "Musso",
      "Nexia",
      "Nubira",
      "Rezzo",
      "Tacuma",
      "Other"
    ],
    "Daihatsu": [
      "Applause",
      "Charade",
      "Charmant",
      "Copen",
      "Cuore",
      "Feroza/Sportrak",
      "Freeclimber",
      "Gran Move",
      "Hijet",
      "MATERIA",
      "Move",
      "Rocky/Fourtrak",
      "Sirion",
      "Terios",
      "TREVIS",
      "YRV",
      "Other"
    ],
    "Dodge": [
      "Avenger",
      "Caliber",
      "Challenger",
      "Charger",
      "Coronet",
      "Dakota",
      "Dart",
      "Demon",
      "Durango",
      "Grand Caravan",
      "Hornet",
      "Journey",
      "Magnum",
      "Neon",
      "Nitro",
      "RAM",
      "Stealth",
      "Viper",
      "Other"
    ],
    "DS": [
      "DS3",
      "DS3 Crossback",
      "DS4",
      "DS4 Crossback",
      "DS5",
      "DS7 (Crossback)",
      "DS9",
      "Nº8",
      "Other"
    ],
    "Ferrari": [
      "208",
      "246",
      "250",
      "275",
      "288",
      "296 GTB",
      "296 GTS",
      "308",
      "328",
      "330",
      "348",
      "360",
      "365",
      "400",
      "412",
      "456",
      "458",
      "488 GTB",
      "488 Pista",
      "488 Spider",
      "512",
      "550",
      "575",
      "599 GTB",
      "599 GTO",
      "599 SA Aperta",
      "612",
      "750",
      "812",
      "California",
      "Daytona",
      "Dino GT4",
      "Enzo Ferrari",
      "F12",
      "F355",
      "F40",
      "F430",
      "F50",
      "F8",
      "FF",
      "GTC4Lusso",
      "LaFerrari",
      "Mondial",
      "Monza",
      "Portofino",
      "Purosangue",
      "Roma",
      "SF90",
      "Superamerica",
      "Testarossa",
      "Other"
    ],
    "Fiat": [
      "124",
      "124 Spider",
      "126",
      "127",
      "130",
      "131",
      "500",
      "500C",
      "500e",
      "500L",
      "500L Cross",
      "500L Living",
      "500L Trekking",
      "500L Urban",
      "500L Wagon",
      "500S",
      "500X",
      "600",
      "600e",
      "Albea",
      "Barchetta",
      "Brava",
      "Bravo",
      "Cinquecento",
      "Coupe",
      "Croma",
      "Dino",
      "Doblo",
      "Ducato",
      "Fiorino",
      "Freemont",
      "Fullback",
      "Grande Panda",
      "Grande Punto",
      "Idea",
      "Linea",
      "Marea",
      "Marengo",
      "Multipla",
      "New Panda",
      "Palio",
      "Panda",
      "Punto",
      "Qubo",
      "Regata",
      "Ritmo",
      "Scudo",
      "Sedici",
      "Seicento",
      "Siena",
      "Spider Europa",
      "Stilo",
      "Strada",
      "Talento",
      "Tempra",
      "Tipo",
      "Topolino",
      "Ulysse",
      "Uno",
      "X 1/9",
      "Other"
    ],
    "Ford": [
      "Aerostar",
      "B-Max",
      "Bronco",
      "Bronco Sport",
      "Capri",
      "C-Max",
      "Cougar",
      "Courier",
      "Crown",
      "Econoline",
      "Econovan",
      "EcoSport",
      "Edge",
      "Escape",
      "Escort",
      "Excursion",
      "Expedition",
      "Explorer",
      "Express",
      "F-100",
      "F-150",
      "F-250",
      "F-350",
      "Fairlane",
      "Falcon",
      "Fiesta",
      "Flex",
      "Focus",
      "Fusion",
      "Galaxy",
      "Granada",
      "Grand C-Max",
      "Grand Tourneo",
      "GT",
      "Ka/Ka+",
      "Kuga",
      "Maverick",
      "Mercury",
      "Mondeo",
      "Mustang",
      "Mustang Mach-E",
      "Orion",
      "Probe",
      "Puma",
      "Puma Gen-E",
      "Ranger",
      "Raptor",
      "Scorpio",
      "Sierra",
      "S-Max",
      "Sportka",
      "Streetka",
      "Taunus",
      "Taurus",
      "Thunderbird",
      "Tourneo (alle)",
      "Tourneo",
      "Tourneo Connect",
      "Tourneo Courier",
      "Tourneo Custom",
      "Transit (All)",
      "Transit",
      "Transit Connect",
      "Transit Courier",
      "Transit Custom",
      "Windstar",
      "Other"
    ],
    "Genesis": [
      "G70",
      "G80",
      "G90",
      "GV60",
      "GV70",
      "GV80",
      "Other"
    ],
    "GMC": [
      "Acadia",
      "Envoy",
      "Safari",
      "Savana",
      "Sierra",
      "Sonoma",
      "Syclone",
      "Terrain",
      "Typhoon",
      "Vandura",
      "Yukon",
      "Other"
    ],
    "Honda": [
      "Accord",
      "Aerodeck",
      "City",
      "Civic",
      "Clarity",
      "Concerto",
      "CR-V",
      "CRX",
      "CR-Z",
      "e",
      "e:Ny1",
      "Element",
      "FR-V",
      "HR-V",
      "Insight",
      "Integra",
      "Jazz",
      "Legend",
      "Logo",
      "NSX",
      "Odyssey",
      "Pilot",
      "Prelude",
      "Ridgeline",
      "S2000",
      "Shuttle",
      "Stream",
      "ZR-V",
      "Other"
    ],
    "Hummer": [
      "H1",
      "H2",
      "H3",
      "Other"
    ],
    "Hyundai": [
      "Accent",
      "Atos",
      "Azera",
      "BAYON",
      "Coupe",
      "Elantra",
      "Excel",
      "Galloper",
      "Genesis",
      "Getz",
      "Grandeur",
      "Grand Santa Fe",
      "H-1",
      "H-100",
      "H-1 Starex",
      "H-200",
      "H350",
      "i10",
      "i20",
      "i30",
      "i40",
      "INSTER",
      "IONIQ",
      "IONIQ 5",
      "IONIQ 6",
      "IONIQ 9",
      "ix20",
      "ix35",
      "ix55",
      "KONA",
      "KONA Elektro",
      "Lantra",
      "Matrix",
      "NEXO",
      "Pony",
      "SANTA FE",
      "Santamo",
      "S-Coupe",
      "SONATA",
      "STARIA",
      "Terracan",
      "Trajet",
      "TUCSON",
      "Veloster",
      "Veracruz",
      "XG 30",
      "XG 350",
      "Other"
    ],
    "INEOS": [
      "Grenadier",
      "Other"
    ],
    "Infiniti": [
      "EX30",
      "EX35",
      "EX37",
      "FX",
      "G35",
      "G37",
      "M30",
      "M35",
      "M37",
      "Q30",
      "Q45",
      "Q50",
      "Q60",
      "Q70",
      "QX30",
      "QX50",
      "QX56",
      "QX60",
      "QX70",
      "QX80",
      "Other"
    ],
    "Isuzu": [
      "Campo",
      "D-Max",
      "Gemini",
      "Midi",
      "PICK UP",
      "Trooper",
      "Other"
    ],
    "Jaguar": [
      "Daimler",
      "E-Pace",
      "E-Type",
      "F-Pace",
      "F-Type",
      "I-Pace",
      "MK II",
      "S-Type",
      "XE",
      "XF",
      "XJ",
      "XJ12",
      "XJ40",
      "XJ6",
      "XJ8",
      "XJR",
      "XJS",
      "XJSC",
      "XK",
      "XK8",
      "XKR",
      "X-Type",
      "Other"
    ],
    "Jeep": [
      "Avenger",
      "Cherokee",
      "CJ",
      "Comanche",
      "Commander",
      "Compass",
      "Gladiator",
      "Grand Cherokee",
      "Patriot",
      "Renegade",
      "Wagoneer",
      "Willys",
      "Wrangler",
      "Other"
    ],
    "Kia": [
      "Besta",
      "Borrego",
      "Carens",
      "Carnival",
      "cee'd / Ceed",
      "cee'd Sportswagon",
      "Cerato",
      "Clarus",
      "Elan",
      "EV3",
      "EV6",
      "EV9",
      "Joice",
      "K2500",
      "K2700",
      "Leo",
      "Magentis",
      "Mentor",
      "Mini",
      "Niro",
      "Niro EV",
      "Opirus",
      "Optima",
      "Picanto",
      "Pregio",
      "Pride",
      "pro cee'd / ProCeed",
      "Retona",
      "Rio",
      "Roadster",
      "Rocsta",
      "Sephia",
      "Shuma",
      "Sorento",
      "Soul",
      "Sportage",
      "Stinger",
      "Stonic",
      "Venga",
      "XCeed",
      "Other"
    ],
    "Koenigsegg": [
      "Agera",
      "CCR",
      "CCXR",
      "Other"
    ],
    "Lamborghini": [
      "Aventador",
      "Countach",
      "Diablo",
      "Espada",
      "Gallardo",
      "Huracán",
      "Jalpa",
      "LM",
      "Miura",
      "Murciélago",
      "Revuelto",
      "Urraco",
      "Urus",
      "Other"
    ],
    "Lancia": [
      "Beta",
      "Dedra",
      "Delta",
      "Flaminia",
      "Flavia",
      "Fulvia",
      "Gamma",
      "Kappa",
      "Lybra",
      "MUSA",
      "Phedra",
      "Prisma",
      "Stratos",
      "Thema",
      "Thesis",
      "Voyager",
      "Ypsilon",
      "Zeta",
      "Other"
    ],
    "Land Rover": [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Freelander",
      "Range Rover",
      "Range Rover Evoque",
      "Range Rover Sport",
      "Range Rover Velar",
      "Serie I",
      "Serie II",
      "Serie III",
      "Other"
    ],
    "Lexus": [
      "CT 200h",
      "ES Series (All)",
      "ES 300",
      "ES 330",
      "ES 350",
      "GS Series (All)",
      "GS 250",
      "GS 300",
      "GS 350",
      "GS 430",
      "GS 450",
      "GS 460",
      "GS F",
      "GX Series (All)",
      "GX 460",
      "GX 470",
      "GX 550",
      "IS Series (All)",
      "IS 200",
      "IS 220",
      "IS 250",
      "IS 300",
      "IS 350",
      "IS-F",
      "LBX",
      "LC 500",
      "LC 500h",
      "LFA",
      "LM",
      "LS Series (All)",
      "LS 400",
      "LS 430",
      "LS 460",
      "LS 500",
      "LS 600",
      "LX Series (All)",
      "LX 450",
      "LX 470",
      "LX 500",
      "LX 570",
      "LX 600",
      "NX Series (All)",
      "NX 200",
      "NX 300",
      "NX 350h",
      "NX 450h",
      "RC Series (All)",
      "RC 200",
      "RC 300",
      "RC 350",
      "RC F",
      "RX Series (All)",
      "RX 200",
      "RX 300",
      "RX 330",
      "RX 350",
      "RX 400",
      "RX 450",
      "RX 500",
      "RZ",
      "SC 400",
      "SC 430",
      "UX",
      "Other"
    ],
    "Lincoln": [
      "Aviator",
      "Continental",
      "LS",
      "Mark",
      "Navigator",
      "Town Car",
      "Other"
    ],
    "Lotus": [
      "340 R",
      "Cortina",
      "Elan",
      "Eletre",
      "Elise",
      "Elite",
      "Emeya",
      "Emira",
      "Esprit",
      "Europa",
      "Evora",
      "Excel",
      "Exige",
      "Super Seven",
      "Other"
    ],
    "Lynk & Co": [
      "01",
      "02",
      "08",
      "Other"
    ],
    "Maserati": [
      "222",
      "224",
      "228",
      "3200",
      "418",
      "420",
      "4200",
      "422",
      "424",
      "430",
      "Biturbo",
      "Ghibli",
      "GranCabrio",
      "Gransport",
      "Granturismo",
      "Grecale",
      "Indy",
      "Karif",
      "Levante",
      "MC12",
      "MC20",
      "Merak",
      "Quattroporte",
      "Shamal",
      "Spyder",
      "Other"
    ],
    "Mazda": [
      "121",
      "2",
      "2 Hybrid",
      "3",
      "323",
      "5",
      "6",
      "626",
      "6e",
      "929",
      "Bongo",
      "B series",
      "BT-50",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-60",
      "CX-7",
      "CX-80",
      "CX-9",
      "Demio",
      "E series",
      "Millenia",
      "MPV",
      "MX-3",
      "MX-30",
      "MX-5",
      "MX-6",
      "Premacy",
      "Protege",
      "RX-6",
      "RX-7",
      "RX-8",
      "Tribute",
      "Xedos",
      "Other"
    ],
    "McLaren": [
      "540C",
      "570GT",
      "570S",
      "600LT",
      "620R",
      "650S",
      "650S Coupé",
      "650S Spider",
      "675LT",
      "675LT Spider",
      "720S",
      "750S",
      "765",
      "765LT",
      "Artura",
      "Elva",
      "GT",
      "MP4-12C",
      "P1",
      "Senna GTR",
      "Speedtail",
      "Other"
    ],
    "Mercedes-Benz": [
      "190",
      "200",
      "220",
      "230",
      "240",
      "250",
      "260",
      "270",
      "280",
      "290",
      "300",
      "320",
      "350",
      "380",
      "400",
      "416",
      "420",
      "450",
      "500",
      "560",
      "600",
      "A-Class (All)",
      "A 140",
      "A 150",
      "A 160",
      "A 170",
      "A 180",
      "A 190",
      "A 200",
      "A 210",
      "A 220",
      "A 250",
      "A 35 AMG",
      "A 45 AMG",
      "B-Class (All)",
      "B 150",
      "B 160",
      "B 170",
      "B 180",
      "B 200",
      "B 220",
      "B 250",
      "B Electric Drive",
      "C-Class (All)",
      "C 160",
      "C 180",
      "C 200",
      "C 220",
      "C 230",
      "C 240",
      "C 250",
      "C 270",
      "C 280",
      "C 300",
      "C 30 AMG",
      "C 320",
      "C 32 AMG",
      "C 350",
      "C 36 AMG",
      "C 400",
      "C 43 AMG",
      "C 450 AMG",
      "C 55 AMG",
      "C 63 AMG",
      "CE-Class (All)",
      "CE 200",
      "CE 220",
      "CE 230",
      "CE 280",
      "CE 300",
      "CE 320",
      "Citan",
      "CLA-Class (All)",
      "CLA 180",
      "CLA 180 Shooting Brake",
      "CLA 200",
      "CLA 200 Shooting Brake",
      "CLA 220",
      "CLA 220 Shooting Brake",
      "CLA 250",
      "CLA 250 Shooting Brake",
      "CLA 350",
      "CLA 35 AMG",
      "CLA 35 AMG Shooting Brake",
      "CLA 45 AMG",
      "CLA 45 AMG Shooting Brake",
      "CLA Shooting Brake",
      "CLC-Class (All)",
      "CLC 160",
      "CLC 180",
      "CLC 200",
      "CLC 220",
      "CLC 230",
      "CLC 250",
      "CLC 350",
      "CL-Class (All)",
      "CL 160",
      "CL 180",
      "CL 200",
      "CL 220",
      "CL 230",
      "CL 320",
      "CL 420",
      "CL 500",
      "CL 55 AMG",
      "CL 600",
      "CL 63 AMG",
      "CL 65 AMG",
      "CLE-Class (All)",
      "CLE 180",
      "CLE 200",
      "CLE 220",
      "CLE 300",
      "CLE 450",
      "CLE 53 AMG",
      "CLK-Class (All)",
      "CLK 200",
      "CLK 220",
      "CLK 230",
      "CLK 240",
      "CLK 270",
      "CLK 280",
      "CLK 320",
      "CLK 350",
      "CLK 430",
      "CLK 500",
      "CLK 55 AMG",
      "CLK 63 AMG",
      "CLS-Class (All)",
      "CLS 220",
      "CLS 220 Shooting Brake",
      "CLS 250",
      "CLS 250 Shooting Brake",
      "CLS 280",
      "CLS 300",
      "CLS 320",
      "CLS 350",
      "CLS 350 Shooting Brake",
      "CLS 400",
      "CLS 400 Shooting Brake",
      "CLS 450",
      "CLS 500",
      "CLS 500 Shooting Brake",
      "CLS 53 AMG",
      "CLS 55 AMG",
      "CLS 63 AMG",
      "CLS 63 AMG Shooting Brake",
      "CLS Shooting Brake",
      "eCitan",
      "E-Class (All)",
      "E 200",
      "E 220",
      "E 230",
      "E 240",
      "E 250",
      "E 260",
      "E 270",
      "E 280",
      "E 290",
      "E 300",
      "E 320",
      "E 350",
      "E 36 AMG",
      "E 400",
      "E 420",
      "E 430",
      "E 43 AMG",
      "E 450",
      "E 50",
      "E 500",
      "E 53 AMG",
      "E 55 AMG",
      "E 60 AMG",
      "E 63 AMG",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQE SUV",
      "EQS",
      "EQS SUV",
      "EQT",
      "EQV",
      "eSprinter",
      "eVito",
      "G-Class (All)",
      "G 230",
      "G 240",
      "G 250",
      "G 270",
      "G 280",
      "G 290",
      "G 300",
      "G 320",
      "G 350",
      "G 400",
      "G 450",
      "G 500",
      "G 55 AMG",
      "G 580",
      "G 63 AMG",
      "G 65 AMG",
      "GLA-Class (All)",
      "GLA 180",
      "GLA 200",
      "GLA 220",
      "GLA 250",
      "GLA 35 AMG",
      "GLA 45 AMG",
      "GLB-Class (All)",
      "GLB 180",
      "GLB 200",
      "GLB 220",
      "GLB 250",
      "GLB 35 AMG",
      "GLC-Class (All)",
      "GLC 200",
      "GLC 220",
      "GLC 250",
      "GLC 300",
      "GLC 350",
      "GLC 400",
      "GLC 43 AMG",
      "GLC 450",
      "GLC 63 AMG",
      "GL-Class (All)",
      "GL 320",
      "GL 350",
      "GL 400",
      "GL 420",
      "GL 450",
      "GL 500",
      "GL 55 AMG",
      "GL 63 AMG",
      "GLE-Class (All)",
      "GLE 250",
      "GLE 300",
      "GLE 350",
      "GLE 400",
      "GLE 43 AMG",
      "GLE 450",
      "GLE 500",
      "GLE 53 AMG",
      "GLE 580",
      "GLE 63 AMG",
      "GLK-Class (All)",
      "GLK 200",
      "GLK 220",
      "GLK 250",
      "GLK 280",
      "GLK 300",
      "GLK 320",
      "GLK 350",
      "GLS-Class (All)",
      "GLS 350",
      "GLS 400",
      "GLS 450",
      "GLS 500",
      "GLS 580",
      "GLS 600",
      "GLS 63",
      "GT-Class (All)",
      "AMG GT",
      "AMG GT C",
      "AMG GT R",
      "AMG GT S",
      "MB 100",
      "ML-Class (All)",
      "ML 230",
      "ML 250",
      "ML 270",
      "ML 280",
      "ML 300",
      "ML 320",
      "ML 350",
      "ML 400",
      "ML 420",
      "ML 430",
      "ML 450",
      "ML 500",
      "ML 55 AMG",
      "ML 63 AMG",
      "R-Class (All)",
      "R 280",
      "R 300",
      "R 320",
      "R 350",
      "R 500",
      "R 63 AMG",
      "S-Class (All)",
      "S 250",
      "S 260",
      "S 280",
      "S 300",
      "S 320",
      "S 350",
      "S 400",
      "S 420",
      "S 430",
      "S 450",
      "S 500",
      "S 55",
      "S 550",
      "S 560",
      "S 580",
      "S 600",
      "S 63 AMG",
      "S 650",
      "S 65 AMG",
      "S 680",
      "SLC-Class (All)",
      "SLC 180",
      "SLC 200",
      "SLC 250",
      "SLC 280",
      "SLC 300",
      "SLC 43 AMG",
      "SL-Class (All)",
      "SL 230",
      "SL 250",
      "SL 280",
      "SL 300",
      "SL 320",
      "SL 350",
      "SL 380",
      "SL 400",
      "SL 420",
      "SL 43 AMG",
      "SL 450",
      "SL 500",
      "SL 55 AMG",
      "SL 560",
      "SL 600",
      "SL 60 AMG",
      "SL 63 AMG",
      "SL 65 AMG",
      "SL 680",
      "SL 70 AMG",
      "SL 73 AMG",
      "SLK-Class (All)",
      "SLK 200",
      "SLK 230",
      "SLK 250",
      "SLK 280",
      "SLK 300",
      "SLK 320",
      "SLK 32 AMG",
      "SLK 350",
      "SLK 55 AMG",
      "SLR",
      "SLS AMG",
      "Sprinter",
      "T-Class",
      "Vaneo",
      "Vario",
      "V-Class (All)",
      "V 200",
      "V 220",
      "V 230",
      "V 250",
      "V 280",
      "V 300",
      "Viano",
      "Vito",
      "X-Class (All)",
      "X 220",
      "X 250",
      "X 350",
      "Other"
    ],
    "MG": [
      "Cyberster",
      "EHS",
      "HS",
      "Marvel R",
      "MG3",
      "MG4",
      "MG5",
      "MGA",
      "MGB",
      "MGF",
      "Midget",
      "Montego",
      "S5",
      "TD",
      "TF",
      "ZR",
      "ZS",
      "ZT",
      "Other"
    ],
    "Mini": [
      "Aceman",
      "Cooper Cabrio",
      "Cooper D Cabrio",
      "Cooper S Cabrio",
      "Cooper SD Cabrio",
      "John Cooper Works Cabrio",
      "One Cabrio",
      "Cooper Clubman",
      "Cooper D Clubman",
      "Cooper S Clubman",
      "Cooper SD Clubman",
      "John Cooper Works Clubman",
      "One Clubman",
      "One D Clubman",
      "Clubvan",
      "Cooper Countryman",
      "Cooper D Countryman",
      "Cooper E Countryman",
      "Cooper S Countryman",
      "Cooper SD Countryman",
      "Cooper SE Countryman",
      "John Cooper Works Countryman",
      "One Countryman",
      "One D Countryman",
      "Cooper Coupé",
      "Cooper S Coupé",
      "Cooper SD Coupé",
      "John Cooper Works Coupé",
      "1000",
      "1300",
      "Cooper",
      "Cooper C",
      "Cooper D",
      "Cooper E",
      "Cooper S",
      "Cooper SD",
      "Cooper SE",
      "John Cooper Works",
      "ONE",
      "One D",
      "One First",
      "Cooper Roadster",
      "Cooper SD Roadster",
      "Cooper S Roadster",
      "John Cooper Works Roadster",
      "Other"
    ],
    "Mitsubishi": [
      "3000 GT",
      "ASX",
      "Canter",
      "Carisma",
      "Colt",
      "Cordia",
      "Cosmos",
      "Diamante",
      "Eclipse",
      "Eclipse Cross",
      "Galant",
      "Galloper",
      "Grandis",
      "i-MiEV",
      "L200",
      "L300",
      "L400",
      "Lancer",
      "Mirage",
      "Montero",
      "Outlander",
      "Pajero",
      "Pajero Pinin",
      "Pick-up",
      "Plug-in Hybrid Outlander",
      "Santamo",
      "Sapporo",
      "Sigma",
      "Space Gear",
      "Space Runner",
      "Space Star",
      "Space Wagon",
      "Starion",
      "Tredia",
      "Other"
    ],
    "Morgan": [
      "3 Wheeler",
      "4/4",
      "Aero 8",
      "Plus 4",
      "Plus 6",
      "Plus 8",
      "Roadster",
      "Other"
    ],
    "Nissan": [
      "100 NX",
      "200 SX",
      "240 SX",
      "280 ZX",
      "300 ZX",
      "350Z",
      "370Z",
      "Almera",
      "Almera Tino",
      "Altima",
      "Ariya",
      "Armada",
      "Bluebird",
      "Cabstar",
      "Cargo",
      "Cherry",
      "Cube",
      "e-NV200",
      "Evalia",
      "Frontier",
      "GT-R",
      "Interstar",
      "Juke",
      "King Cab",
      "Kubistar",
      "Laurel",
      "Leaf",
      "Maxima",
      "Micra",
      "Murano",
      "Navara",
      "Note",
      "NP 300",
      "NV200",
      "NV250",
      "NV300",
      "NV400",
      "Pathfinder",
      "Patrol",
      "PickUp",
      "Pixo",
      "Prairie",
      "Primastar",
      "Primera",
      "Pulsar",
      "Qashqai",
      "Qashqai+2",
      "Quest",
      "Sentra",
      "Serena",
      "Silvia",
      "Skyline",
      "Sunny",
      "Terrano",
      "Tiida",
      "Titan",
      "Townstar",
      "Trade",
      "Urvan",
      "Vanette",
      "X-Trail",
      "Other"
    ],
    "Opel": [
      "Adam",
      "Agila",
      "Ampera",
      "Ampera-e",
      "Antara",
      "Arena",
      "Ascona",
      "Astra",
      "Astra Electric",
      "Calibra",
      "Campo",
      "Cascada",
      "Cavalier",
      "Combo",
      "Combo Electric",
      "Combo Life",
      "Commodore",
      "Corsa",
      "Crossland (X)",
      "Diplomat",
      "Frontera",
      "Grandland (X)",
      "GT",
      "Insignia",
      "Insignia CT",
      "Kadett",
      "Karl",
      "Manta",
      "Meriva",
      "Mokka",
      "Mokka-e",
      "Mokka X",
      "Monterey",
      "Monza",
      "Movano",
      "Nova",
      "Omega",
      "Pick Up Sportscap",
      "Rekord",
      "Rocks-e",
      "Senator",
      "Signum",
      "Sintra",
      "Speedster",
      "Tigra",
      "Vectra",
      "Vivaro",
      "Zafira",
      "Zafira Electric",
      "Zafira Life",
      "Zafira Tourer",
      "Other"
    ],
    "Pagani": [
      "Huayra",
      "Zonda",
      "Other"
    ],
    "Peugeot": [
      "1007",
      "104",
      "106",
      "107",
      "108",
      "2008",
      "204",
      "205",
      "206",
      "207",
      "208",
      "3008",
      "301",
      "304",
      "305",
      "306",
      "307",
      "308",
      "309",
      "4007",
      "4008",
      "404",
      "405",
      "406",
      "407",
      "408",
      "5008",
      "504",
      "505",
      "508",
      "604",
      "605",
      "607",
      "806",
      "807",
      "Bipper",
      "Bipper Tepee",
      "Boxer",
      "e-208",
      "e-Rifter",
      "e-Traveller",
      "Expert",
      "Expert Tepee",
      "iOn",
      "J5",
      "Partner",
      "Partner Tepee",
      "RCZ",
      "Rifter",
      "TePee",
      "Traveller",
      "Other"
    ],
    "Polestar": [
      "1",
      "2",
      "3",
      "4",
      "Other"
    ],
    "Porsche": [
      "356",
      "912",
      "914",
      "918",
      "924",
      "928",
      "944",
      "959",
      "962",
      "968",
      "Boxster",
      "Carrera GT",
      "Cayenne",
      "Cayman",
      "Macan",
      "Panamera",
      "911",
      "930",
      "964",
      "991",
      "992",
      "993",
      "996",
      "997",
      "Taycan",
      "Other"
    ],
    "Renault": [
      "Alaskan",
      "Alpine A110",
      "Alpine A310",
      "Alpine V6",
      "Arkana",
      "Austral",
      "Avantime",
      "Captur",
      "Clio",
      "Coupe",
      "Espace",
      "Express",
      "Fluence",
      "Fuego",
      "Grand Espace",
      "Grand Kangoo",
      "Grand Kangoo E-TECH",
      "Grand Modus",
      "Grand Scenic",
      "Kadjar",
      "Kangoo",
      "Kangoo E-TECH",
      "Koleos",
      "Laguna",
      "Latitude",
      "Mascott",
      "Master",
      "Megane",
      "Megane E-TECH",
      "Modus",
      "P 1400",
      "R 11",
      "R 14",
      "R 18",
      "R 19",
      "R 20",
      "R 21",
      "R 25",
      "R 30",
      "R 4",
      "R 5",
      "R 6",
      "R 9",
      "Rafale",
      "Rapid",
      "Safrane",
      "Scenic",
      "Scenic E-TECH",
      "Spider",
      "Symbioz",
      "Talisman",
      "Trafic",
      "Twingo",
      "Twizy",
      "Vel Satis",
      "Wind",
      "ZOE",
      "Other"
    ],
    "Rolls-Royce": [
      "Corniche",
      "Cullinan",
      "Dawn",
      "Flying Spur",
      "Ghost",
      "Park Ward",
      "Phantom",
      "Silver Cloud",
      "Silver Dawn",
      "Silver Seraph",
      "Silver Shadow",
      "Silver Spirit",
      "Silver Spur",
      "Spectre",
      "Wraith",
      "Other"
    ],
    "Rover": [
      "100",
      "111",
      "114",
      "115",
      "200",
      "213",
      "214",
      "216",
      "218",
      "220",
      "25",
      "400",
      "414",
      "416",
      "418",
      "420",
      "45",
      "600",
      "618",
      "620",
      "623",
      "75",
      "800",
      "820",
      "825",
      "827",
      "City Rover",
      "Metro",
      "Montego",
      "SD",
      "Streetwise",
      "Other"
    ],
    "Saab": [
      "90",
      "900",
      "9000",
      "9-3",
      "9-4X",
      "9-5",
      "96",
      "9-7X",
      "99",
      "Other"
    ],
    "Seat": [
      "Alhambra",
      "Altea",
      "Arona",
      "Arosa",
      "Ateca",
      "Cordoba",
      "Exeo",
      "Ibiza",
      "Inca",
      "Leon",
      "Malaga",
      "Marbella",
      "Mii",
      "Tarraco",
      "Terra",
      "Toledo",
      "Other"
    ],
    "Skoda": [
      "105",
      "120",
      "130",
      "135",
      "Citigo",
      "Elroq",
      "Enyaq",
      "Fabia",
      "Favorit",
      "Felicia",
      "Forman",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Octavia",
      "Pick-up",
      "Praktik",
      "Rapid",
      "Roomster",
      "Scala",
      "Superb",
      "Yeti",
      "Other"
    ],
    "Smart": [
      "#1",
      "#3",
      "#5",
      "Crossblade",
      "ForFour",
      "ForTwo",
      "Roadster",
      "Other"
    ],
    "SsangYong": [
      "Actyon",
      "Family",
      "Korando",
      "Kyron",
      "MUSSO",
      "REXTON",
      "Rodius",
      "Tivoli",
      "Torres",
      "XLV",
      "Other"
    ],
    "Subaru": [
      "B9 Tribeca",
      "Baja",
      "BRZ",
      "Crosstrek",
      "Forester",
      "Impreza",
      "Justy",
      "Legacy",
      "Levorg",
      "Libero",
      "Outback",
      "Solterra",
      "SVX",
      "Trezia",
      "Tribeca",
      "Vivio",
      "WRX STI",
      "XT",
      "XV",
      "Other"
    ],
    "Suzuki": [
      "(SX4) S-Cross",
      "Across",
      "Alto",
      "Baleno",
      "Cappuccino",
      "Carry",
      "Celerio",
      "Grand Vitara",
      "Ignis",
      "iK-2",
      "Jimny",
      "Kizashi",
      "Liana",
      "LJ",
      "SJ Samurai",
      "Splash",
      "Super-Carry",
      "Swace",
      "Swift",
      "SX4",
      "Vitara",
      "Wagon R+",
      "X-90",
      "Other"
    ],
    "Tata": [
      "Indica",
      "Indigo",
      "Nano",
      "Safari",
      "Sumo",
      "Telcoline",
      "Telcosport",
      "Xenon",
      "Other"
    ],
    "Tesla": [
      "Model 3",
      "Model S",
      "Model X",
      "Model Y",
      "Roadster",
      "Other"
    ],
    "Toyota": [
      "4-Runner",
      "Alphard",
      "Auris",
      "Auris Touring Sports",
      "Avalon",
      "Avensis",
      "Avensis Verso",
      "Aygo (X)",
      "bZ4X",
      "Camry",
      "Carina",
      "Celica",
      "C-HR",
      "Corolla",
      "Corolla Cross",
      "Corolla Verso",
      "Cressida",
      "Crown",
      "Dyna",
      "FCV",
      "FJ",
      "Fortuner",
      "GR86",
      "GT86",
      "Hiace",
      "Highlander",
      "Hilux",
      "IQ",
      "Land Cruiser",
      "Lite-Ace",
      "Matrix",
      "Mirai",
      "MR 2",
      "Paseo",
      "Picnic",
      "Previa",
      "Prius",
      "Prius+",
      "Proace (Verso)",
      "Proace City",
      "Proace Max",
      "Proace Verso Electric",
      "RAV 4",
      "Sequoia",
      "Sienna",
      "Starlet",
      "Supra",
      "Tacoma",
      "Tercel",
      "Tundra",
      "Urban Cruiser",
      "Verso",
      "Verso-S",
      "Yaris",
      "Yaris Cross",
      "Other"
    ],
    "TVR": [
      "Chimaera",
      "Griffith",
      "Tuscan",
      "Other"
    ],
    "Volkswagen": [
      "181",
      "Amarok",
      "Arteon",
      "Beetle",
      "Bora",
      "Buggy",
      "Caddy",
      "Caddy Maxi",
      "CC",
      "Corrado",
      "Crafter",
      "Eos",
      "e-up!",
      "Fox",
      "Golf (All)",
      "Golf",
      "Golf Plus",
      "Golf Sportsvan",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.6",
      "ID.7",
      "ID. Buzz",
      "Iltis",
      "Jetta",
      "Käfer",
      "Karmann Ghia",
      "LT",
      "Lupo",
      "New Beetle",
      "Passat (All)",
      "Passat",
      "Passat Alltrack",
      "Passat CC",
      "Passat Variant",
      "Phaeton",
      "Polo",
      "Routan",
      "Santana",
      "Scirocco",
      "Sharan",
      "T1",
      "T2",
      "T3 Caravelle",
      "T3 Kombi",
      "T3 Multivan",
      "T3 other",
      "T4 California",
      "T4 Caravelle",
      "T4 Kombi",
      "T4 Multivan",
      "T4 other",
      "T5 California",
      "T5 Caravelle",
      "T5 Kombi",
      "T5 Multivan",
      "T5 other",
      "T5 Shuttle",
      "T5 Transporter",
      "T6 California",
      "T6 Caravelle",
      "T6 Kombi",
      "T6 Multivan",
      "T6 other",
      "T6 Transporter",
      "T7 California",
      "T7 Caravelle",
      "T7 Kombi",
      "T7 Multivan",
      "T7 other",
      "Taigo",
      "Taro",
      "Tayron",
      "T-Cross",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "Touran",
      "T-Roc",
      "up!",
      "Vento",
      "XL1",
      "Other"
    ],
    "Volvo": [
      "240",
      "244",
      "245",
      "262",
      "264",
      "340",
      "360",
      "440",
      "460",
      "480",
      "740",
      "744",
      "745",
      "760",
      "780",
      "850",
      "855",
      "940",
      "944",
      "945",
      "960",
      "965",
      "Amazon",
      "C30",
      "C40",
      "C70",
      "EC40",
      "ES90",
      "EX30",
      "EX40",
      "EX90",
      "Polar",
      "S40",
      "S60",
      "S60 Cross Country",
      "S70",
      "S80",
      "S90",
      "V40",
      "V40 Cross Country",
      "V50",
      "V60",
      "V60 Cross Country",
      "V70",
      "V90",
      "V90 Cross Country",
      "XC40",
      "XC60",
      "XC70",
      "XC90",
      "Other"
    ],
  },
};

export const fetchCarBrands = async () => {
  try {
    const brands = Object.keys(carData.carBrands).sort();
    return brands;
  } catch (error) {
    console.error("Error fetching car brands:", error);
    return [];
  }
};

export const fetchCarModels = async (brandName) => {
  if (!brandName) return [];

  try {
    const formattedBrand = brandName.trim();
    console.log(`Fetching models for brand: "${formattedBrand}"`);
    
    const models = carData.carBrands[formattedBrand] || [];
    console.log(`Found ${models.length} models for ${formattedBrand}`);
    
    return models;
  } catch (error) {
    console.error(`Error fetching models for ${brandName}:`, error);
    return [];
  }
};
